version: '3.8'

services:
  metric_benchmark:
    build:
      context: .
      dockerfile: ./metric_benchmark/Dockerfile
    image: kampkelly/metric-benchmark:latest
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres
      - metric_simulator

  metric_simulator:
    build:
      context: .
      dockerfile: ./metric_simulator/Dockerfile
    image: kampkelly/metric-simulator:latest
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:latest"
    ports:
      - "6378:6379"

  postgres:
    image: "postgres:17"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-password}
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres

volumes:
  postgres_data:
  grafana_data:
