apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metric-benchmark
spec:
  type: {{ .Values.metricBenchmark.service.type }}
  ports:
    - port: {{ .Values.metricBenchmark.service.port }}
      targetPort: 8000
  selector:
    app: metric-benchmark
