apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metric-simulator
spec:
  type: {{ .Values.metricSimulator.service.type }}
  ports:
    - port: {{ .Values.metricSimulator.service.port }}
      targetPort: 8001
  selector:
    app: metric-benchmark
